# Generated by Django 5.0 on 2023-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='rating',
            field=models.TextField(max_length=10, verbose_name='rating'),
        ),
    ]
